# Generated by Django 5.2.8 on 2025-11-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodemo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
